name: Build and Release Box64

on:
  workflow_dispatch:
  release:
  push:
    paths:
      - "**/*.c"
      - "**/*.h"
      - "**/*.S"
      - "**/*.py"
      - "CMakeLists.txt"
      - "**/*.yml"
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - "**/*.c"
      - "**/*.h"
      - "**/*.S"
      - "**/*.py"
      - "CMakeLists.txt"
      - "**/*.yml"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [X64, RISCV, RK3588, ARM64, ANDROID, TERMUX, LARCH64, ANDROID_GLIBC, WOW64]
        type: [Release, Trace, StaticBuild, Box32]
        os: [ubuntu-latest, ubuntu-22.04-arm]
        exclude:
          - platform: ANDROID
            type: StaticBuild
          - platform: TERMUX
            type: StaticBuild
          - platform: X64
            type: StaticBuild
          - platform: ANDROID
            type: Box32
          - platform: TERMUX
            type: Box32
          - platform: X64
            os: ubuntu-22.04-arm
          - platform: RISCV
            os: ubuntu-22.04-arm
          - platform: RK3588
            os: ubuntu-latest
          - platform: ARM64
            os: ubuntu-latest
          - platform: ANDROID
            os: ubuntu-22.04-arm
          - platform: TERMUX
            os: ubuntu-22.04-arm
          - platform: LARCH64
            os: ubuntu-22.04-arm
          - platform: ANDROID_GLIBC
            os: ubuntu-latest
          - platform: WOW64
            os: ubuntu-latest
          - platform: WOW64
            type: Trace
          - platform: WOW64
            type: StaticBuild
          - platform: WOW64
            type: Box32
          - platform: ANDROID
            type: Trace
          - platform: TERMUX
            type: Trace
          - platform: LARCH64
            type: Trace

    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout Box64 Repository"
        uses: actions/checkout@v4

      # [ ... seu build steps ... ]
      # MANTENHA OS MESMOS STEPS DO BUILD QUE VOCÊ JÁ TEM AQUI
      # NÃO REMOVA NENHUM PASSO DO BUILD JÁ EXISTENTE
      # ISSO INCLUI OS UPLOADS DE ARTEFATOS INTERNOS
      # ISSO GARANTE QUE NADA QUEBRE

  publish-rat:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload box64-latest-micewine.rat to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: box64-latest-micewine.rat
          asset_name: box64-latest-micewine.rat
          asset_content_type: application/octet-stream

